### PR TITLE
SDK and testnet upgrade

### LINKED ISSUE #276: Upgrade SDK to v 0.18.0

### LINKED ISSUE #277: Upgrade sdk, fixes #276 ; Remove AESEncryption service

### LINKED ISSUE #292: New testnet config
Nodes, faucet, explorer update...

### PR DESCRIPTION
**Pull request by decentraliser**
* upgrade SDK to v0.18.0, fixes #276
* remove AESEncryptionService, fixes #277
* Testnet upgrade, fixes #292
* Move user data storage folder to `/home/.symbol-desktop-wallet`
* Rename accounts to profiles, wallets to accounts #304

### CODE REVIEW

**Comment by fboucquez** [comment]
Should we merge https://github.com/nemfoundation/symbol-desktop-wallet/pull/301 to this pr first?

**Comment by decentraliser** [comment]
yes we should merge #301, and do the renaming

**Comment by evias** [comment]
agreed

**Comment by evias** [comment]
note on the breaking of the account process, all users will have to go through account process due to the breaking storage change ; account creation process must be fixed

**Pull request merged**
