### PR TITLE
Add style files of all components scoped:

### LINKED ISSUE #273: Add scoped less import for PeerSelector
1. path in `src/components/PeerSelector/PeerSelector.vue` ,
i will suggest that if you want to change the iview styles in this component.please add `scoped`,like this `<style lang="less" scoped></style>`

### LINKED ISSUE #307: Add scoped to the style of all components
Hey, friends.
At present, the project has reached a very good stage, but due to the previous rapid development, there are still some problems left. I hope we can improve these problems.
# About Less
With the development of desktop wallet, more and more components will appear. There may be some style conflicts between components. For example, you add `scoped` to the newly developed component styles, but you will find that the components you write are affected by the style files you don't know where, because we didn't add `scoped` to some old component styles. like [here](https://github.com/nemfoundation/symbol-desktop-wallet/blob/master/src/components/MosaicBalanceList/MosaicBalanceList.less#L258),[here ](https://github.com/nemfoundation/symbol-desktop-wallet/blob/master/src/components/PeerSelector/PeerSelector.vue#L86),[here](https://github.com/nemfoundation/symbol-desktop-wallet/blob/master/src/components/LanguageSelector/LanguageSelector.vue#L13) and so on.  
the first one it changed the styles of iview tables, but the iview components we use in other components do not need these styles.what should we change at this time?  
there are many places like the second and the third, this will cause overall style pollution.  
for example, we are developing a component, but the default style is that when we finished the template
image  
We haven't started writing component styles yet.  
There are many similar problems, I find some as the follows:  
image  
image
  
About more details, you can see [here](https://vuejs.org/v2/style-guide/index.html#Component-style-scoping-essential)
We can see that Vue officials highly recommend that we do  that  add styles `scoped`,besides, common.less  should be updated, a lot of styles are out of date because of the transformation of our code, many old codes are very confusing to us.

## what i will do?
     1. add scoped to all components   and  adjust style
     2. update some common.less 

## benefits?
There won't be many strange problems in CSS, and even if they do, we can easily fix them in CSS scope, and in most cases, we don't need to consider affecting other elements,because of the `scoped`,  and we could global change global style, local change local style.

### LINKED ISSUE #321: Mnemonic Import copy/paste bug
When pasting a 24-words mnemonic into the account import page i get the following bug as shown in screenshot ..

Screenshot 2020-05-02 at 10 28 30 PM

### LINKED ISSUE #347: Different styles of selectors
image
image
image

### LINKED ISSUE #348: Styles of modal look strange
image
image
image
image
image

### LINKED ISSUE #350: MosaicBalanceList and transactionList should have a better display
MosaicBalanceList 
image
transactionList 
image

### PR DESCRIPTION
**Pull request by vincent-lee90**
fixes #273 (fixes #307) (fixes #321):
  *Add style files of all components scoped
  *Refactor style of PeerSelector
  *Refactor style of common Modal
  *Refactor style of MosaicBalanceList
  *Improved the display of upper right
  *Extracted the codes of DebugConsole
  *Extracted style codes of iview into a file named 'custom-iview'
Correct part of UI display:
  * Select component is used uniformly, fixes #347,
  * Changed the styles of MosaicBalanceList and TransactionList ,fixes #350
  * Changed some style of modals ,fixes #348
  *Improved some styles, as the follows:
## Before change
微信图片_20200502115041
微信图片_202005021150411
微信图片_202005021150412
微信图片_202005021150413
微信图片_202005021150414
微信图片_202005021150415
微信图片_202005021150416
微信图片_202005021150417
微信图片_202005021150418
## After change
微信图片_20200502120604
微信图片_202005021206041
微信图片_202005021206042
微信图片_202005021206043
微信图片_202005021206044
微信图片_202005021206045
微信图片_202005021206046
微信图片_202005021206047
微信图片_202005021206048
微信图片_202005021206049
微信图片_2020050212060410

I know that this PR may involve a lot of files, but most of them are view layers, which has nothing to do with our business logic. 
If you have any questions or suggestion, you are welcome to communicate with me. 
Thank you for your review

### CODE REVIEW

**Comment by vincent-lee90** [comment]
fix  #321

**Comment by vincent-lee90** [comment]
fix #273

**Comment by vincent-lee90** [comment]
fix #307

**Comment by vincent-lee90** [comment]
## Why did  i refactor  the style and html of  PeerSelector?
When i was adding `scoped` to the components ,  i found there are some different places to write the style code of the component which is named `PeerSelector` , such as [here](https://github.com/nemfoundation/symbol-desktop-wallet/blob/1261a13dec9fa027585182faa7441d42560021da/src/views/layout/PageLayout/PageLayout.common.less#L123)  [here](https://github.com/nemfoundation/symbol-desktop-wallet/blob/1261a13dec9fa027585182faa7441d42560021da/src/views/layout/PageLayout/PageLayout.common.less#L185), and after i put them into a file , they look messy.
So I  decided to refactor the style and the html of the component which is named `PeerSelector`

**Comment by evias** [comment]
I requested this PR to be split into several smaller PRs.

The argumentation is fine - yes, it makes sense to improve our CSS and add the scoped attribute to our style tags **but** this PR is _too big_ and cannot be reviewed correctly without affecting other features.

**Please, re-open PRs implementing these changes per-component, not applying it to multiple components at once.**

**Pull request closed without merging**
