### PR TITLE
Change display of PeerSelector

### PR DESCRIPTION
**Pull request by vincent-lee90**
I  have changed the display of the PeerSelector. 
maybe you will find that the editing function of some nodes has disappeared.
Don't worry, I put them in the next pr

### CODE REVIEW

**Comment by vincent-lee90** [comment]
fixed prettier

**Comment by evias** [comment]
Settings link does not work ..

**Comment by vincent-lee90** [comment]
> Settings link does not work ..

yes,it won't work, becase the pr#339  has not been finished
This PR is mainly to modify the appearance

**Comment by evias** [comment]
While 339 is in work, please make the link redirect to the current Settings page.

**Pull request merged**
